from __future__ import annotations

from gitprbot.db.schema import JobRow

TOOL_USE_RULES = """
RULES:
- Always emit code changes as a unified diff for apply_patch — never rewrite whole files.
- Never include secrets, tokens, or credentials in any output.
- Run tests after every patch; do not commit or push without green tests.
- If tests fail after the repair cap, stop and report — do not loop forever.
- The apply_patch tool uses `git apply` — ensure your diff has correct context lines.
"""


def build_system_prompt(memory_context: str, job_type: str) -> str:
    base = f"""You are a skilled software engineer agent working inside a GitHub repository.
You have tools to read files, search code, apply patches, run tests, and manage git.

{TOOL_USE_RULES}

Your goal: understand the task, write a correct code change, verify it with tests, then commit.
"""
    if memory_context:
        base += f"\n## Context from prior work\n{memory_context}\n"
    return base


def build_task_instruction(job: JobRow) -> str:
    parts = [f"Repo: {job.repo_full_name}"]

    if job.trigger_type == "webhook_pr" and job.pr_number:
        parts.append(f"PR #: {job.pr_number}")
    elif job.trigger_type in ("webhook_comment", "webhook_issue") and job.issue_number:
        parts.append(f"Issue #: {job.issue_number}")

    if job.actor:
        parts.append(f"Requested by: {job.actor}")

    if job.instruction:
        parts.append(f"\nTask:\n{job.instruction}")
    else:
        parts.append("\nTask: Review and address any issues in this PR/issue.")

    return "\n".join(parts)


def build_repair_prompt(failure_output: str, iteration: int) -> str:
    return (
        f"Tests failed (attempt {iteration}). Output:\n\n"
        f"```\n{failure_output[:3000]}\n```\n\n"
        "Diagnose the failure and apply a patch to fix it. "
        "Focus on the root cause shown in the error output."
    )


def build_draft_pr_body(job: JobRow, last_failure: str) -> str:
    return f"""⚠️ **Agent could not make tests pass** — human review needed.

**Job:** `{job.job_id}`
**Trigger:** {job.trigger_type}
**Instruction:** {job.instruction or '(none)'}

**Last test failure:**
```
{last_failure[:2000]}
```

The agent applied its best attempt at a fix but tests did not go green within the repair cap.
Please review the diff and either continue from here or close this PR.
"""


def build_pr_body(job: JobRow, test_output: str) -> str:
    return f"""Automated PR by gitprbot.

**Job:** `{job.job_id}`
**Trigger:** {job.trigger_type}
**Instruction:** {job.instruction or '(none)'}

**Test results (passing):**
```
{test_output[:1500]}
```

---
*Generated by [gitprbot](https://github.com/ilovehhhyn/gitprbot)*
"""
